//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavyBeats_C_.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NavyBeats_C_.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        internal static string btnCrear {
            get {
                return ResourceManager.GetString("btnCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string btnEliminar {
            get {
                return ResourceManager.GetString("btnEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar.
        /// </summary>
        internal static string btnEntrar {
            get {
                return ResourceManager.GetString("btnEntrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        internal static string btnEnviar {
            get {
                return ResourceManager.GetString("btnEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string btnGuardar {
            get {
                return ResourceManager.GetString("btnGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        internal static string btnModificar {
            get {
                return ResourceManager.GetString("btnModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abril.
        /// </summary>
        internal static string lblAbril {
            get {
                return ResourceManager.GetString("lblAbril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agosto.
        /// </summary>
        internal static string lblAgosto {
            get {
                return ResourceManager.GetString("lblAgosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apertura.
        /// </summary>
        internal static string lblApertura {
            get {
                return ResourceManager.GetString("lblApertura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asunto.
        /// </summary>
        internal static string lblAsunto {
            get {
                return ResourceManager.GetString("lblAsunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calendario.
        /// </summary>
        internal static string lblCalendario {
            get {
                return ResourceManager.GetString("lblCalendario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cierre.
        /// </summary>
        internal static string lblCierre {
            get {
                return ResourceManager.GetString("lblCierre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conf. Contraseña.
        /// </summary>
        internal static string lblConfContra {
            get {
                return ResourceManager.GetString("lblConfContra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta.
        /// </summary>
        internal static string lblConsulta {
            get {
                return ResourceManager.GetString("lblConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string lblContra {
            get {
                return ResourceManager.GetString("lblContra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        internal static string lblCorreo {
            get {
                return ResourceManager.GetString("lblCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string lblDescripcion {
            get {
                return ResourceManager.GetString("lblDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dia Seleccionado.
        /// </summary>
        internal static string lblDiaSeleccionado {
            get {
                return ResourceManager.GetString("lblDiaSeleccionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diciembre.
        /// </summary>
        internal static string lblDiciembre {
            get {
                return ResourceManager.GetString("lblDiciembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disponibilidad de Musico.
        /// </summary>
        internal static string lblDispoMusico {
            get {
                return ResourceManager.GetString("lblDispoMusico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Domingo.
        /// </summary>
        internal static string lblDomingo {
            get {
                return ResourceManager.GetString("lblDomingo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enero.
        /// </summary>
        internal static string lblEnero {
            get {
                return ResourceManager.GetString("lblEnero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estilos.
        /// </summary>
        internal static string lblEstilos {
            get {
                return ResourceManager.GetString("lblEstilos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Febrero.
        /// </summary>
        internal static string lblFebrero {
            get {
                return ResourceManager.GetString("lblFebrero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formulario de Soporte.
        /// </summary>
        internal static string lblFormSoporte {
            get {
                return ResourceManager.GetString("lblFormSoporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de Usuarios.
        /// </summary>
        internal static string lblGestion {
            get {
                return ResourceManager.GetString("lblGestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Idioma.
        /// </summary>
        internal static string lblIdioma {
            get {
                return ResourceManager.GetString("lblIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incidencia.
        /// </summary>
        internal static string lblIncidencia {
            get {
                return ResourceManager.GetString("lblIncidencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jueves.
        /// </summary>
        internal static string lblJueves {
            get {
                return ResourceManager.GetString("lblJueves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Julio.
        /// </summary>
        internal static string lblJulio {
            get {
                return ResourceManager.GetString("lblJulio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Junio.
        /// </summary>
        internal static string lblJunio {
            get {
                return ResourceManager.GetString("lblJunio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Latitud.
        /// </summary>
        internal static string lblLatitud {
            get {
                return ResourceManager.GetString("lblLatitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Local.
        /// </summary>
        internal static string lblLocal {
            get {
                return ResourceManager.GetString("lblLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Longitud.
        /// </summary>
        internal static string lblLongitud {
            get {
                return ResourceManager.GetString("lblLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lunes.
        /// </summary>
        internal static string lblLunes {
            get {
                return ResourceManager.GetString("lblLunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mapa.
        /// </summary>
        internal static string lblMapa {
            get {
                return ResourceManager.GetString("lblMapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Martes.
        /// </summary>
        internal static string lblMartes {
            get {
                return ResourceManager.GetString("lblMartes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marzo.
        /// </summary>
        internal static string lblMarzo {
            get {
                return ResourceManager.GetString("lblMarzo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mayo.
        /// </summary>
        internal static string lblMayo {
            get {
                return ResourceManager.GetString("lblMayo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Miercoles.
        /// </summary>
        internal static string lblMiercoles {
            get {
                return ResourceManager.GetString("lblMiercoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipio.
        /// </summary>
        internal static string lblMunicipio {
            get {
                return ResourceManager.GetString("lblMunicipio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Musico.
        /// </summary>
        internal static string lblMusico {
            get {
                return ResourceManager.GetString("lblMusico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string lblNombre {
            get {
                return ResourceManager.GetString("lblNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del musico.
        /// </summary>
        internal static string lblNombreMusico {
            get {
                return ResourceManager.GetString("lblNombreMusico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificación.
        /// </summary>
        internal static string lblNoti {
            get {
                return ResourceManager.GetString("lblNoti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Noviembre.
        /// </summary>
        internal static string lblNoviembre {
            get {
                return ResourceManager.GetString("lblNoviembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Octubre.
        /// </summary>
        internal static string lblOctubre {
            get {
                return ResourceManager.GetString("lblOctubre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol.
        /// </summary>
        internal static string lblRol {
            get {
                return ResourceManager.GetString("lblRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sabado.
        /// </summary>
        internal static string lblSabado {
            get {
                return ResourceManager.GetString("lblSabado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un idioma.
        /// </summary>
        internal static string lblSelecIdioma {
            get {
                return ResourceManager.GetString("lblSelecIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Septiembre.
        /// </summary>
        internal static string lblSeptiembre {
            get {
                return ResourceManager.GetString("lblSeptiembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin Evento.
        /// </summary>
        internal static string lblSinEvento {
            get {
                return ResourceManager.GetString("lblSinEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soporte Técnico.
        /// </summary>
        internal static string lblSoporte {
            get {
                return ResourceManager.GetString("lblSoporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        internal static string lblTel {
            get {
                return ResourceManager.GetString("lblTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        internal static string lblTipo {
            get {
                return ResourceManager.GetString("lblTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios del Sistema.
        /// </summary>
        internal static string lblUsuario {
            get {
                return ResourceManager.GetString("lblUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Viernes.
        /// </summary>
        internal static string lblViernes {
            get {
                return ResourceManager.GetString("lblViernes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visualización de Locales.
        /// </summary>
        internal static string lblVisuLocales {
            get {
                return ResourceManager.GetString("lblVisuLocales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes eliminar tu propio usuario..
        /// </summary>
        internal static string msgAutoEliminar {
            get {
                return ResourceManager.GetString("msgAutoEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Completa todos los campos correctamente..
        /// </summary>
        internal static string msgCompleta {
            get {
                return ResourceManager.GetString("msgCompleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        internal static string msgConfirmar {
            get {
                return ResourceManager.GetString("msgConfirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña no coincide..
        /// </summary>
        internal static string msgContra {
            get {
                return ResourceManager.GetString("msgContra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron coordenadas para este músico..
        /// </summary>
        internal static string msgCoordMusico {
            get {
                return ResourceManager.GetString("msgCoordMusico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron coordenadas para este restaurante..
        /// </summary>
        internal static string msgCoordRestaurante {
            get {
                return ResourceManager.GetString("msgCoordRestaurante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estas seguro de eliminar al usuario?.
        /// </summary>
        internal static string msgEliminar {
            get {
                return ResourceManager.GetString("msgEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string msgError {
            get {
                return ResourceManager.GetString("msgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes modificar tu propio usuario..
        /// </summary>
        internal static string msgModificar {
            get {
                return ResourceManager.GetString("msgModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes permiso para acceder a esta opción..
        /// </summary>
        internal static string msgPermiso {
            get {
                return ResourceManager.GetString("msgPermiso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario y/o contraseña incorrecto..
        /// </summary>
        internal static string msgUsuarioContra {
            get {
                return ResourceManager.GetString("msgUsuarioContra", resourceCulture);
            }
        }
    }
}
