//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavyBeats_C_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like_Restaurant_Publication
    {
        public string publish_date { get; set; }
        public int restaurant_id { get; set; }
        public int publication_id { get; set; }
    
        public virtual Publication Publication { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
