//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavyBeats_C_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int message_id { get; set; }
        public string text { get; set; }
        public Nullable<System.DateTime> publish_date { get; set; }
        public Nullable<System.DateTime> reading_date { get; set; }
        public Nullable<int> chat_id { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual Chat Chat { get; set; }
        public virtual Users Users { get; set; }
    }
}
