//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavyBeats_C_.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NaivyBeatsEntities : DbContext
    {
        public NaivyBeatsEntities()
            : base("name=NaivyBeatsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chat> Chat { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Comment_Restaurant_Publication> Comment_Restaurant_Publication { get; set; }
        public virtual DbSet<Like_Restaurant_Publication> Like_Restaurant_Publication { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<Municipality> Municipality { get; set; }
        public virtual DbSet<Musician> Musician { get; set; }
        public virtual DbSet<Offer_dir> Offer_dir { get; set; }
        public virtual DbSet<Offer_In> Offer_In { get; set; }
        public virtual DbSet<Offer_in_Styles> Offer_in_Styles { get; set; }
        public virtual DbSet<Publication> Publication { get; set; }
        public virtual DbSet<Restaurant> Restaurant { get; set; }
        public virtual DbSet<Style> Style { get; set; }
        public virtual DbSet<Super_User> Super_User { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<time> time { get; set; }
        public virtual DbSet<User_Style> User_Style { get; set; }
        public virtual DbSet<User_Time> User_Time { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Valorar> Valorar { get; set; }
    }
}
