//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavyBeats_C_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer_dir
    {
        public int offer_id { get; set; }
        public string publish_date { get; set; }
        public Nullable<int> salary { get; set; }
        public string event_date { get; set; }
        public Nullable<byte> agreement { get; set; }
        public Nullable<byte> done { get; set; }
        public Nullable<int> restaurant_id { get; set; }
        public Nullable<int> musician_id { get; set; }
    
        public virtual Musician Musician { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
