//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavyBeats_C_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer_In
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offer_In()
        {
            this.Offer_in_Styles = new HashSet<Offer_in_Styles>();
        }
    
        public int offer_in_id { get; set; }
        public string publish_date { get; set; }
        public Nullable<int> salary { get; set; }
        public string event_date { get; set; }
        public Nullable<int> music_id_final { get; set; }
        public Nullable<int> restaurant_id { get; set; }
        public string description { get; set; }
    
        public virtual Musician Musician { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offer_in_Styles> Offer_in_Styles { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
