//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavyBeats_C_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Publication()
        {
            this.Comment_Restaurant_Publication = new HashSet<Comment_Restaurant_Publication>();
            this.Like_Restaurant_Publication = new HashSet<Like_Restaurant_Publication>();
        }
    
        public int publication_id { get; set; }
        public Nullable<System.DateTime> publication_date { get; set; }
        public string description { get; set; }
        public string multimedia_content { get; set; }
        public Nullable<int> user_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment_Restaurant_Publication> Comment_Restaurant_Publication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Like_Restaurant_Publication> Like_Restaurant_Publication { get; set; }
        public virtual Musician Musician { get; set; }
    }
}
